version: '2.1'

services:
  awsserver:
    build: awsserver
    image: dnabic/awsserver:v0.0.1
    hostname: moto
    container_name: moto
    ports:
      - "5000:5000"
    labels:
      app: moto
    networks:
      -  aws_net
    command: moto_server ec2 -H 0.0.0.0
#    healthcheck:
      #      test: ["CMD-SHELL", "curl -f http://localhost:5000"]
      #      test: ["CMD", "curl","-f" "http://localhost:5000"]
      #      interval: 7s
      #      timeout: 2s
      #      retries: 2
  awssetup:
    build: awssetup
    image: dnabic/awssetup:v0.0.2
    labels:
      app: awssetup
    networks:
      -  aws_net
    volumes:
      - ./awssetup/.aws/:/root/.aws
    environment:
      HTTP_PROXY: http://awsserver:5000
      HTTPS_PROXY: http://awsserver:5000
    command: aws ec2 describe-instances --endpoint-url http://awsserver:5000
    depends_on:
      awsserver:
        condition: service_started
      #          condition: service_healthy

  awssetup-terraform:
    build: terraform
    image: dnabic/terraform:v0.0.8
    labels:
      app: terraform
    networks:
      -  aws_net
    environment:
      HTTP_PROXY: http://awsserver:5000
      HTTPS_PROXY: http://awsserver:5000
      AWS_ACCESS_KEY_ID: the_key
      AWS_SECRET_ACCESS_KEY: the_secret
      AWS_DEFAULT_REGION: us-east-1
    command: apply
    depends_on:
      awsserver:
        condition: service_started
networks:
  aws_net:
    driver: bridge
